spring:
  application:
    name: custom-food-details-service
  datasource:
    url: jdbc:mysql://172.18.4.177:3306/spartans
    username: chirag
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  #jpa:
    #hibernate:
      #ddl-auto: update
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.3.44:8761/eureka/