server:
  port: 9002
spring:
  application:
    name: feign-progress-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.3.44:8761/eureka/
management: 
  endpoints: 
    web: 
      exposure: 
        include: 'hystrix.stream'
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 160000000
        read-timeout: 160000000